cleanup

diff --git a/.github/workflows/mobile.yml b/.github/workflows/mobile.yml
--- a/.github/workflows/mobile.yml
+++ b/.github/workflows/mobile.yml
@@ -92,6 +92,21 @@ jobs:
             "$ANDROID_NDK_ROOT" \
             "$JAVA_HOME" \
             | haxelib run lime setup android  
+
+          TARGET_DIR=".haxelib/openfl/git/src/openfl"
+
+          if [ -d "$TARGET_DIR" ]; then
+            echo "Patching all files in $TARGET_DIR..."
+
+            # Find all files and run sed on them
+            find "$TARGET_DIR" -type f -exec sed -i 's/lime\.ui\.FileDialogFilter/lime.ui.FileDialog/g' {} +
+
+            echo "Done. Verifying random changes:"
+            grep -rn "lime.ui.FileDialog" "$TARGET_DIR" | head -n 10 || true
+          else
+            echo "Directory not found: $TARGET_DIR"
+            exit 1
+          fi
           
           haxelib list
 
@@ -116,9 +131,9 @@ jobs:
           echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
           echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/29.0.14206865" >> $GITHUB_ENV
 
-      - name: Setup Android
+      - name: Build Apk
         run: |
-          mkdir -p ~/.gradle
+         mkdir -p ~/.gradle
           echo "org.gradle.jvmargs=-Xmx5g -XX:MaxMetaspaceSize=1536m -Dfile.encoding=UTF-8" > ~/.gradle/gradle.properties
           echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
           echo "org.gradle.parallel=false" >> ~/.gradle/gradle.properties
@@ -126,26 +141,6 @@ jobs:
           echo "android.splits.abi.enable=false" >> ~/.gradle/gradle.properties
           echo "JAVA_TOOL_OPTIONS=-Xmx5g" >> $GITHUB_ENV
           echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
-
-      - name: Patch All OpenFL Files
-        run: |
-          TARGET_DIR=".haxelib/openfl/git/src/openfl"
-
-          if [ -d "$TARGET_DIR" ]; then
-            echo "Patching all files in $TARGET_DIR..."
-
-            # Find all files and run sed on them
-            find "$TARGET_DIR" -type f -exec sed -i 's/lime\.ui\.FileDialogFilter/lime.ui.FileDialog/g' {} +
-
-            echo "Done. Verifying random changes:"
-            grep -rn "lime.ui.FileDialog" "$TARGET_DIR" | head -n 10 || true
-          else
-            echo "Directory not found: $TARGET_DIR"
-            exit 1
-          fi
-         
-      - name: Build APK
-        run: |
          haxelib run lime clean android
          haxelib run lime build android -final -release \
            --certificate-path="keystore.jks" \
@@ -154,11 +149,6 @@ jobs:
            --certificate-alias-password="${{ secrets.KEY_PASSWORD }}" \
            -clean ${{ github.event.inputs.android_flags }}
          find . -name "*.apk"
-
-      - name: debug
-        run: |
-         #find . -name "AndroidManifest.xml"
-         cat export/release/android/bin/app/src/main/AndroidManifest.xml
          
       - name: Save cache
         if: ${{ success() && (github.event_name == 'push' || github.event.inputs.rebuild_cache != 'Yes' || github.event_name == 'push') }}
